### ISSUE TITLE
Hp4 False triggers

### ISSUE THREAD

**Issue by Mauri740** [robertzak133/unified-btc-reverse#4]
hi, great job! Is it possible to create a PIR sensitivity adjustment for the HP4 or reduce false triggers due to excessive camera sensitivity? I think this is the worst flaw of these cameras. I have tons of browning t-cameras, but this problem is making me hate their products. Too many and unjustified false triggers are a big problem. Thank you!!

**Comment by robertzak133** [comment]
Thanks.  Unfortunately, there is no firmware fix that will reduce the PIR sensitivity on the HP4 (or Edge, or HP5).  The PIR sensor in this (these) cameras goes through a discrete amplifier and threshold detector which has only two sensitivity settings, set by resistor/capacitor choices on the PCB.  The only thing the firmware can do is select between these two options. 

[An earlier camera model – the Advantage – now discontinued – had an PIR sensor with an integrated, digitally configurable amplifier and threshold detector.  It would have been relatively easy to tune the sensitivity on this camera.  Unfortunately (IMO), Browning moved away from this PIR sensor in more recent cameras, I suspect to reduce cost and/or supply chain issues.]

The best I can offer as a consolation is my blog post on other ways to reduce false triggers.   See: https://winterberrywildlife.ouroneacrefarm.com/2021/10/12/avoiding-false-triggers-in-trail-cameras/
