### ISSUE TITLE
Night Threshold broken on BTC-7E-HP4

### ISSUE THREAD

**Issue by olafmatt** [robertzak133/unified-btc-reverse#7]
Noticed that on BTC-7E-HP4 cameras the Night Threshold option reacts weird. On the default "Standard" setting my cameras switch to night (B/W plus illumination) a lot earlier than with stock firmware. Even the "low light" setting causes switch to night mode where the stock firmware would still be on day mode. The "no light" setting works correctly.

**Comment by robertzak133** [comment]
Thanks for this bug report.  I'll set up a more controlled test environment and see if I can reproduce.

**Comment by robertzak133** [comment]
Confirmed bug.  Simple solution -- in aperture.c when declaring threshold constants for different cameras, I grouped the HP4s with the Edges in an #if def.  They should have been grouped with the HP5, as they share values. Confirmed this by inspecting annotated factory firmware for all three camera types from Ghidra.  Easiest fix ever ;)   Testing and including in next major release

**Comment by robertzak133** [comment]
Tested.  Included in release of 2024-05-06
